#!/bin/bash

function assign_user_role_credential {
    TOP_DIR=$1
    source $TOP_DIR/openrc admin admin
    #set -x
    serviceTenantID=`keystone tenant-list | grep "service" | awk '{print $2}'`
    serviceRoleID=`keystone role-list | grep "service" | awk '{print $2}'`
    adminRoleID=`keystone role-list | grep "admin" | awk '{print $2}'`
    keystone user-role-add --user nova --tenant $serviceTenantID --role $serviceRoleID
    keystone user-role-add --user neutron --tenant $serviceTenantID --role $adminRoleID
}

function create_ext_net {
    TOP_DIR=$1
    source $TOP_DIR/stackrc
    EXT_NET_NAME=$EXT_NET_NAME
    EXT_NET_SUBNET_NAME=$EXT_NET_SUBNET_NAME
    EXT_NET_GATEWAY=$EXT_NET_GATEWAY
    EXT_NET_ALLOCATION_POOL_START=$EXT_NET_ALLOCATION_POOL_START
    EXT_NET_ALLOCATION_POOL_END=$EXT_NET_ALLOCATION_POOL_END
    EXT_NET_CIDR=$EXT_NET_CIDR
    EXT_NET_MASK=$EXT_NET_MASK
    
    source $TOP_DIR/openrc neutron service
    neutron net-create --router:external=true --shared $EXT_NET_NAME
    neutron subnet-create --ip_version 4 --gateway $EXT_NET_GATEWAY --name $EXT_NET_SUBNET_NAME --allocation-pool start=$EXT_NET_ALLOCATION_POOL_START,end=$EXT_NET_ALLOCATION_POOL_END $EXT_NET_NAME $EXT_NET_CIDR/$EXT_NET_MASK
    subnet_id=`neutron net-list | grep "$EXT_NET_NAME" | awk '{print $6}'`

}

function create_nfp_gbp_resources {
   
   TOP_DIR=$1
   source $TOP_DIR/openrc neutron service
   gbp network-service-policy-create --network-service-params type=ip_pool,name=vip_ip,value=nat_pool svc_mgmt_fip_policy
   gbp service-profile-create --servicetype LOADBALANCER --insertion-mode l3 --shared True --service-flavor haproxy --vendor NFP lb_profile
   gbp service-profile-create --servicetype FIREWALL --insertion-mode l3 --shared True --service-flavor service_vendor=vyos,device_type=None --vendor NFP fw_profile
   gbp group-create svc_management_ptg --service_management True
}

function get_router_namespace {
    
    TOP_DIR=$1
    source $TOP_DIR/openrc neutron service

    GROUP="svc_management_ptg"
    echo "GroupName: $GROUP"

    l2p_id=`gbp ptg-show svc_management_ptg | grep l2_policy_id | awk '{print $4}'`
    l3p_id=`gbp l2p-show $l2p_id | grep l3_policy_id | awk '{print $4}'`
    RouterId=`gbp l3p-show $l3p_id | grep routers | awk '{print $4}'`
}

function copy_nfp_files_and_start_process {

    TOP_DIR=$1
    cd /opt/stack/gbp/gbpservice/nfp
    sudo cp -r  bin/nfp /usr/bin/
    sudo chmod +x /usr/bin/nfp
    sudo rm -rf /etc/nfp_*
    sudo cp -r  bin/nfp_orch_agent.ini /etc/
    sudo cp -r  bin/nfp_proxy_agent.ini /etc/
    sudo cp -r  bin/nfp_config_orch.ini /etc/
    sudo cp -r  bin/proxy.ini /etc/nfp_proxy.ini
    sudo cp -r  bin/nfp_proxy /usr/bin/

    IpAddr=127.0.0.1
    echo "Configuring proxy.ini .... with rest_server_address as $IpAddr"
    sudo sed -i "s/rest_server_address=*.*/rest_server_address=$IpAddr/g" /etc/nfp_proxy.ini
    sudo sed -i "s/rest_server_port= *.*/rest_server_port=8080/g" /etc/nfp_proxy.ini
    ipnetns_router=`sudo ip netns |grep $RouterId`

    source $TOP_DIR/functions-common

    echo "Starting orchestrator  >>>> under screen named : orchestrator"
    run_process orchestrator "sudo /usr/bin/nfp  --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --config-file /etc/nfp_orch_agent.ini --log-file /opt/stack/logs/nfp_orchestrator.log"
    sleep 1
   
    echo "Starting proxy_agent  >>>> under screen named : proxy_agent"
    run_process proxy_agent "sudo /usr/bin/nfp --config-file /etc/nfp_proxy_agent.ini --log-file /opt/stack/logs/nfp_proxy_agent.log"
    sleep 1

    echo "Starting proxy server under Router : $RouterId namespace $ipnetns_router >>>> under screen named : proxy"
    run_process proxy "sudo ip netns exec $ipnetns_router /usr/bin/nfp_proxy --config-file=/etc/nfp_proxy.ini"


    echo "Starting config_orch  >>>> under screen named : config_orch"
    run_process config_orch "sudo /usr/bin/nfp  --config-file /etc/nfp_config_orch.ini --config-file /etc/neutron/neutron.conf --log-file /opt/stack/logs/nfp_config_orch.log"
    sleep 1

    cd base_configurator/api
    sudo python setup.py develop
    echo "Starting base_configurator  >>>> under screen named : base_configurator"
    run_process base_configurator "cd /opt/stack/gbp/gbpservice/nfp/base_configurator/api;sudo ip netns exec $ipnetns_router pecan serve config.py" 
    sleep 1

    echo "Running gbp-db-manage"

    source $TOP_DIR/openrc neutron service

    gbp-db-manage --config-file /etc/neutron/neutron.conf upgrade head
    sleep 2
    echo "Configuration success ... "

}

function configure_nfp_firewall {
    sudo cp -r /opt/stack/gbp/gbpservice/nfp/Automation-Scripts/oc_noop_firewall_driver /opt/stack/neutron-fwaas/neutron_fwaas/services/firewall/drivers/linux/.
    echo "Firewall Agent topic changed from :L3_AGENT_TOPIC to oc-firewall-agent Topic"
    sudo sed -i "s/topics.L3_AGENT/'oc-firewall-agent'/g" /opt/stack/neutron-fwaas/neutron_fwaas/services/firewall/fwaas_plugin.py

}
function configure_nfp_basic.sh {
    assign_user_role_credential $1
    create_ext_net $1
                        
}
function nfp_setup {
    configure_nfp_basic.sh $1 
    create_nfp_gbp_resources $1
    get_router_namespace $1 
    copy_nfp_files_and_start_process $1

}
